sa_snowflake:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('ACCOUNT') }}"
      user: "{{ env_var('USER') }}"
      role: "{{ env_var('ROLE') }}"

      # Keypair config
      private_key_path: "{{ env_var('KEY_PATH') }}"
      # or private_key instead of private_key_path
      private_key_passphrase: "{{ env_var('PASSPHRASE') }}"

      database: "{{ env_var('DATABASE') }}"
      warehouse: "{{ env_var('WAREHOUSE') }}"
      schema: dbt_trouze
      threads: 4
      client_session_keep_alive: False

      # optional
      connect_retries: 0 # default 0
      connect_timeout: 10 # default: 10
      retry_on_database_errors: False # default: false
      retry_all: False  # default: false
      reuse_connections: True # default: True if client_session_keep_alive is False, otherwise None
    prod:
      type: snowflake
      account: "{{ env_var('ACCOUNT') }}"
      user: "{{ env_var('USER') }}"
      role: "{{ env_var('ROLE') }}"

      # Keypair config
      private_key_path: "{{ env_var('KEY_PATH') }}"
      # or private_key instead of private_key_path
      private_key_passphrase: "{{ env_var('PASSPHRASE') }}"

      database: "{{ env_var('DATABASE') }}"
      warehouse: "{{ env_var('WAREHOUSE') }}"
      schema: public
      threads: 4
      client_session_keep_alive: False

      # optional
      connect_retries: 0 # default 0
      connect_timeout: 10 # default: 10
      retry_on_database_errors: False # default: false
      retry_all: False  # default: false
      reuse_connections: True # default: True if client_session_keep_alive is False, otherwise None